name: muraita_2_0
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: 3.2.1
  cloud_firestore: ^3.1.18
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  file_picker: ^4.6.1
  firebase_auth: ^3.3.20
  firebase_core: ^1.19.1
  firebase_database: ^9.0.18
  firebase_messaging: ^12.0.0
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.9.3
  flutter_layout_grid: ^2.0.1
  flutter_lints: ^2.0.0
  flutter_local_notifications: ^9.7.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.0.0-dev.9
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.1.0
  go_router: ^3.1.1
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  like_button: ^2.0.4
  open_file: ^3.2.1
  path: ^1.8.1
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  pinput: ^2.2.11
  rxdart: ^0.27.4
  sembast: ^3.2.0+1
  sembast_web: ^2.0.1+1
  sqflite: ^2.0.2+1
  timeago: ^3.2.2
  user_profile_avatar: ^0.1.1

dev_dependencies:
  flutter_config: null
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app_icon.png"
  image_path_android: "assets/app_icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app_icon_background.png"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    # Used for Golden Image tests
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    # Add all product images
    - assets/products/
    - assets/
    - .env
